### ISSUE TITLE
【質問】応用編 p16 4. グラフ表示の動作確認方法

### ISSUE THREAD

**Issue by grace2riku** [b5g-ex/jssst2022_tutorial#3]
温湿度センサを入手したので応用編のハンズオンをやっています。
応用編 p16 4. グラフ表示で質問させてください。

【質問】
P17, p18のコードを実行してもp18右下のグラフが表示されません。

P17, p18のコードを書いたあとプログラム実行すればグラフは表示されるでしょうか?
それともプログラム実行の後になにか操作が必要でしょうか?
もしP17, p18のコードを実行するための事前条件(ほかのコードを実行していないこと)などあれば教えてください。

【その他、補足説明】
・P16までの温湿度センサのハンズオンは確認できているのでハードウェア的な問題ではないと考えています。

・P17, p18のコードを実行すると:okの表示となりますがグラフが表示されない状況です。

**Comment by 32hero** [comment]
@grace2riku 随分遅くなりました。
p15までの温湿度が計測まではできている状態かと思います。
原因は定かではありませんが、特定のブラウザ：Braveを使用している場合に、正しく表示できない場合があるようです。

**Comment by grace2riku** [comment]
@32hero ご回答ありがとうございます。

解決できました。
グラフが描画確認できなかった理由は
1コードブロックに応用編p17・p18のコードをまとめて記述し実行していたからでした。

1コードブロックにp17のコードを記述→実行でグラフエリアが描画され、
次のコードブロックにp18のコードを記述→実行で温度・湿度がグラフに描画されました。

ご回答ありがとうございました。

**Comment by grace2riku** [comment]
resolved
